# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4556956144d3c6ab7c0ca398cbf673274bf37dd16b883e6a79159f29bc10b505b501d131492dae4ef968d2c3f27cb36be66fb078817ff448172214dd99dba89c

test:
  secret_key_base: ebdacb2a0900533b2082e89d26ac931100fbff0b7b92752755cfeeb009792194c39b828aaebb04ea547e505df7463b4efa092ec12be0b461d8c319d6365c0e5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
